-- CREATE A RECORD THAT SAVES THE VALUES RETURNED FROM THE OLTP TABLE BY A FUNCTION.
-- CREATE A FUNCION THAT GETS THE NECESARY ROWS FROM THE OLTP DB.
-- CREATE A PROCEDURE THAT INSERTS THE ROWS GETED FROM THE OLTP DB TO THE OLAP DB.

CREATE OR REPLACE PACKAGE PK_ETL_TIEMPO
IS 
   FUNCTION FN_OBTENER_TIEMPOS RETURN SYS_REFCURSOR;
   PROCEDURE SP_INSERTAR_TIEMPOS(MSJ OUT VARCHAR2);
   
END;

CREATE OR REPLACE PACKAGE BODY PK_ETL_TIEMPO
IS 
    FUNCTION FN_OBTENER_TIEMPOS RETURN SYS_REFCURSOR
    IS
        DATOS_TIEMPOS SYS_REFCURSOR;
    BEGIN
        OPEN DATOS_TIEMPOS FOR SELECT 
        OLTP_REPRO.ID_REPRODUCCION, 
        LOWER(TO_CHAR(OLTP_REPRO.FECHA_REPRODUCCION, 'MONTH', 'NLS_DATE_LANGUAGE = SPANISH')),
        TO_NUMBER(TO_CHAR(OLTP_REPRO.FECHA_REPRODUCCION, 'DD')),
        TO_NUMBER(TO_CHAR(OLTP_REPRO.FECHA_REPRODUCCION, 'YYYY')),
        LOWER(TO_CHAR(OLTP_REPRO.FECHA_REPRODUCCION, 'DAY', 'NLS_DATE_LANGUAGE = SPANISH'))
        FROM C##_OLTP_ADMIN_DBII_PROJECT.REPRODUCCIONES OLTP_REPRO
        WHERE NOT EXISTS
        (SELECT * FROM DIM_TIEMPO DT WHERE DT.ID_TIEMPO = OLTP_REPRO.ID_REPRODUCCION);

        RETURN DATOS_TIEMPOS;        
    END;
    
    PROCEDURE SP_INSERTAR_TIEMPOS(MSJ OUT VARCHAR2)
    IS
        TYPE FILA IS RECORD(
            TIEMPO_ID DIM_TIEMPO.ID_TIEMPO%TYPE, -- NUMBER
            MES DIM_TIEMPO.MES%TYPE, -- VARCHAR2(100 BYTE)
            DIA DIM_TIEMPO.DÍA%TYPE, -- NUMBER
            ANIO DIM_TIEMPO.AÑO%TYPE, -- NUMBER
            NOMBRE_DIA DIM_TIEMPO.NOMBRE_DIA%TYPE -- VARCHAR(25)
        );
        FILA_TIEMPO FILA;
    
        DATOS_OBTENIDOS SYS_REFCURSOR;
    BEGIN
        DATOS_OBTENIDOS := FN_OBTENER_TIEMPOS;
      
        LOOP
            FETCH DATOS_OBTENIDOS INTO FILA_TIEMPO;
            EXIT WHEN DATOS_OBTENIDOS%NOTFOUND;
            
            INSERT INTO DIM_TIEMPO VALUES 
            (FILA_TIEMPO.TIEMPO_ID, 
            FILA_TIEMPO.MES, 
            FILA_TIEMPO.DIA,
            FILA_TIEMPO.ANIO,
            FILA_TIEMPO.NOMBRE_DIA);
        
            /*        
            DBMS_OUTPUT.PUT_LINE('ID DEL TIEMPO: '|| FILA_TIEMPO.TIEMPO_ID);
            DBMS_OUTPUT.PUT_LINE('MES: ' || FILA_TIEMPO.MES); 
            DBMS_OUTPUT.PUT_LINE('DIA: ' || FILA_TIEMPO.DIA);
            DBMS_OUTPUT.PUT_LINE('AÑO: ' || FILA_TIEMPO.ANIO);
            DBMS_OUTPUT.PUT_LINE('NOMBRE DEL DIA: ' || FILA_TIEMPO.NOMBRE_DIA);
            DBMS_OUTPUT.PUT_LINE(CHR(10));
            */
            
        END LOOP;     
        CLOSE DATOS_OBTENIDOS;
        COMMIT;
        MSJ := 'EJECUCIÓN DE ETL TIEMPO COMPLETADO CORRECTAMENTE.';
        
        EXCEPTION
            WHEN OTHERS THEN
                MSJ := 'ERROR EN EL ETL TIEMPO: ' || SQLERRM;
                ROLLBACK;
    END;
END;

DECLARE
    MENSAJE VARCHAR2(500);
BEGIN
    PK_ETL_TIEMPO.SP_INSERTAR_TIEMPOS(MENSAJE);
    DBMS_OUTPUT.PUT_LINE(MENSAJE);
END;

DELETE FROM DIM_TIEMPO;
SET SERVEROUTPUT ON;
SELECT * FROM DIM_TIEMPO;