CREATE OR REPLACE PACKAGE PK_ETL_USUARIOS IS 
    FUNCTION FN_OBTENER_USUARIOS RETURN SYS_REFCURSOR;
    PROCEDURE SP_INSERTAR_USUARIOS(MSJ OUT VARCHAR2);
END;

CREATE OR REPLACE PACKAGE BODY PK_ETL_USUARIOS IS 
    FUNCTION FN_OBTENER_USUARIOS RETURN SYS_REFCURSOR IS 
        DATOS_USUARIOS SYS_REFCURSOR;
    BEGIN
        OPEN DATOS_USUARIOS FOR 
        SELECT
            u.ID_USUARIO,
            u.NOMBRE_USUARIO,
            u.FECHA_REGISTRO,
            p.NOMBRE
        FROM
            C##_OLTP_ADMIN_DBII_PROJECT.USUARIOS u
        LEFT JOIN
            C##_OLTP_ADMIN_DBII_PROJECT.PLANES p ON u.ID_PLAN = p.ID_PLAN
        WHERE NOT EXISTS
            (SELECT * FROM DIM_USUARIO WHERE DIM_USUARIO.ID_USUARIO = u.ID_USUARIO);
        RETURN DATOS_USUARIOS;
    END;

    PROCEDURE SP_INSERTAR_USUARIOS(MSJ OUT VARCHAR2) IS
        TYPE FILA IS RECORD(
            ID_USUARIO DIM_USUARIO.ID_USUARIO%TYPE,
            NOMBRE DIM_USUARIO.NOMBRE%TYPE,
            FECHA_REGISTRO DIM_USUARIO.FECHA_REGISTRO%TYPE,
            PLAN_NOMBRE DIM_USUARIO.PLAN_NOMBRE%TYPE
        );
        
        FILA_USUARIO FILA;
        DATOS_OBTENIDOS SYS_REFCURSOR;
    BEGIN
        DATOS_OBTENIDOS := FN_OBTENER_USUARIOS;
    
        LOOP
            FETCH DATOS_OBTENIDOS INTO FILA_USUARIO;
            EXIT WHEN DATOS_OBTENIDOS%NOTFOUND;
            
            INSERT INTO DIM_USUARIO VALUES 
            (FILA_USUARIO.ID_USUARIO, NVL(UPPER(TRIM(TRAILING '.' FROM FILA_USUARIO.NOMBRE)), 'SIN DEFINIR'),
            NVL(FILA_USUARIO.FECHA_REGISTRO, SYSDATE),
            NVL(UPPER(TRIM(TRAILING '.' FROM FILA_USUARIO.PLAN_NOMBRE)), 'NO ENCONTRADO'));
        
        /*
            DBMS_OUTPUT.PUT_LINE('ID USUARIO: '|| FILA_USUARIO.ID_USUARIO);
            DBMS_OUTPUT.PUT_LINE('NOMBRE DEL USUARIO: ' || NVL(UPPER(TRIM(TRAILING '.' FROM FILA_USUARIO.NOMBRE)), 'SIN DEFINIR'));
            DBMS_OUTPUT.PUT_LINE('FECHA DE REGISTRO: ' || NVL(FILA_USUARIO.FECHA_REGISTRO, SYSDATE));
            DBMS_OUTPUT.PUT_LINE('NOMBRE DEL PLAN: ' || NVL(UPPER(TRIM(TRAILING '.' FROM FILA_USUARIO.PLAN_NOMBRE)), 'SIN DEFINIR'));
            DBMS_OUTPUT.PUT_LINE(CHR(10));
            */
        
        END LOOP;
        
        CLOSE DATOS_OBTENIDOS;
        COMMIT;
        MSJ := 'EJECUCIÓN DE ETL USUARIO COMPLETADO CORRECTAMENTE.';
        
        EXCEPTION
            WHEN OTHERS THEN
                MSJ := 'ERROR EN EL ETL USUARIO: ' || SQLERRM;
                ROLLBACK;
        END;
END;

DECLARE
    MENSAJE VARCHAR2(500);
BEGIN
    PK_ETL_USUARIOS.SP_INSERTAR_USUARIOS(MENSAJE);
    DBMS_OUTPUT.PUT_LINE(MENSAJE);
END;

DELETE FROM DIM_USUARIO;
SELECT * FROM DIM_USUARIO;

