CREATE OR REPLACE PACKAGE PK_ETL_PLANES IS
    FUNCTION FN_OBTENER_PLANES(QUERY_ORIGIN_TBL_PLAN VARCHAR2) RETURN SYS_REFCURSOR;
    PROCEDURE SP_INSERTAR_PLANES(QUERY_ORIGIN_TBL_PLAN VARCHAR2 ,MSJ OUT VARCHAR2);
END;

CREATE OR REPLACE PACKAGE BODY PK_ETL_PLANES IS 

    FUNCTION FN_OBTENER_PLANES(QUERY_ORIGIN_TBL_PLAN VARCHAR2) RETURN SYS_REFCURSOR
    IS
        DATOS_PLANES SYS_REFCURSOR;
    BEGIN
        OPEN DATOS_PLANES FOR QUERY_ORIGIN_TBL_PLAN;
        RETURN DATOS_PLANES;
    END;
    
    PROCEDURE SP_INSERTAR_PLANES(QUERY_ORIGIN_TBL_PLAN VARCHAR2, MSJ OUT VARCHAR2) IS
        TYPE FILA IS RECORD(
            ID_PLAN DIM_PLAN.ID_PLAN%TYPE,
            NOMBRE DIM_PLAN.NOMBRE%TYPE,
            PRECIO DIM_PLAN.PRECIO%TYPE
        );
        FILA_PLAN FILA;
        
        DATOS_OBTENIDOS SYS_REFCURSOR;
    BEGIN
        DATOS_OBTENIDOS := FN_OBTENER_PLANES(QUERY_ORIGIN_TBL_PLAN);
        
        LOOP
            FETCH DATOS_OBTENIDOS INTO FILA_PLAN;
            EXIT WHEN DATOS_OBTENIDOS%NOTFOUND;
            
            INSERT INTO DIM_PLAN VALUES(
                 FILA_PLAN.ID_PLAN,
                 FILA_PLAN.NOMBRE,
                 FILA_PLAN.PRECIO);
           
        END LOOP;
        
        CLOSE DATOS_OBTENIDOS;
        COMMIT;
        MSJ := 'EJECUCIÓN DE ETL PLAN COMPLETADO CORRECTAMENTE.';
        
        EXCEPTION
            WHEN OTHERS THEN
                MSJ := 'ERROR EN EL ETL PLAN: ' || SQLERRM;
                ROLLBACK;
        END;
END;
    
DECLARE 
    MENSAJE VARCHAR2(500);
    
    QUERY_ORIGIN_TBL_PLAN VARCHAR2(1500) :=  'SELECT 
            OLTP_PLANES.ID_PLAN,
            NVL(UPPER(TRIM(TRAILING ''.'' FROM OLTP_PLANES.NOMBRE)), ''SIN DEFINIR''),
            NVL(OLTP_PLANES.PRECIO, 0)
            FROM C##_OLTP_ADMIN_DBII_PROJECT.PLANES OLTP_PLANES
            WHERE NOT EXISTS
            (SELECT * FROM DIM_PLAN WHERE DIM_PLAN.ID_PLAN = OLTP_PLANES.ID_PLAN)';
BEGIN
    PK_ETL_PLANES.SP_INSERTAR_PLANES(QUERY_ORIGIN_TBL_PLAN ,MENSAJE);
    DBMS_OUTPUT.PUT_LINE(MENSAJE);
END;

DELETE FROM DIM_PLAN;
SELECT * FROM DIM_PLAN;