CREATE OR REPLACE PACKAGE PK_ETL_ARTISTAS IS 
    FUNCTION FN_OBTENER_ARTISTAS RETURN SYS_REFCURSOR;
    PROCEDURE SP_INSERTAR_ARTISTAS(MSJ OUT VARCHAR2);
END;

CREATE OR REPLACE PACKAGE BODY PK_ETL_ARTISTAS IS
    FUNCTION FN_OBTENER_ARTISTAS RETURN SYS_REFCURSOR IS 
        DATOS_ARTISTAS SYS_REFCURSOR;
    BEGIN
        OPEN DATOS_ARTISTAS FOR 
        SELECT 
            OTLP_ARTISTAS.ID_ARTISTA,
            OTLP_ARTISTAS.NOMBRE
        FROM C##_OLTP_ADMIN_DBII_PROJECT.ARTISTAS OTLP_ARTISTAS;
    
    RETURN DATOS_ARTISTAS;
    
    END;
    
    PROCEDURE SP_INSERTAR_ARTISTAS(MSJ OUT VARCHAR2) IS
    TYPE FILA IS RECORD(
        ID_ARTISTA DIM_ARTISTA.ID_ARTISTA%TYPE,
        NOMBRE DIM_ARTISTA.NOMBRE%TYPE
    );
    FILA_ARTISTA FILA;
    
    DATOS_OBTENIDOS SYS_REFCURSOR;
    BEGIN
        
        DATOS_OBTENIDOS := FN_OBTENER_ARTISTAS;
        
        LOOP
            FETCH DATOS_OBTENIDOS INTO FILA_ARTISTA;
            EXIT WHEN DATOS_OBTENIDOS%NOTFOUND;
            
           INSERT INTO DIM_ARTISTA (ID_ARTISTA, NOMBRE)
           SELECT FILA_ARTISTA.ID_ARTISTA, NVL(UPPER(TRIM(TRAILING '.' FROM FILA_ARTISTA.NOMBRE)), 'SIN DEFINIR')
           FROM DUAL 
           WHERE NOT EXISTS (
           SELECT 1 FROM DIM_ARTISTA D 
           WHERE D.ID_ARTISTA = FILA_ARTISTA.ID_ARTISTA
           );
           
           /*
            DBMS_OUTPUT.PUT_LINE('ID DEL ARTISTA: ' || FILA_ARTISTA.ID_ARTISTA);
            DBMS_OUTPUT.PUT_LINE('NOMBRE DEL ARTISTA: ' || NVL(UPPER(TRIM(TRAILING '.' FROM FILA_ARTISTA.NOMBRE)), 'SIN DEFINIR'));
            DBMS_OUTPUT.PUT_LINE(CHR(10));
            */
        END LOOP;
    
        CLOSE DATOS_OBTENIDOS;
        COMMIT;
        MSJ := 'EJECUCIÓN DE ETL ARTISTA COMPLETADO CORRECTAMENTE.';
        
        EXCEPTION
            WHEN OTHERS THEN
                MSJ := 'ERROR EN EL ETL ARTISTA: ' || SQLERRM;
                ROLLBACK;
    END;
END;
    
DECLARE 
    MENSAJE VARCHAR2(500);
BEGIN
    PK_ETL_ARTISTAS.SP_INSERTAR_ARTISTAS(MENSAJE);
    DBMS_OUTPUT.PUT_LINE(MENSAJE);
END;

DELETE FROM DIM_ARTISTA;
SELECT * FROM DIM_ARTISTA;