-- Creating the user from 
CREATE USER C##_OLTP_ADMIN_DBII_PROJECT
IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

CREATE USER C##_OLAP_ADMIN_DBII_PROJECT
IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

CREATE ROLE C##_ADMIN_DBII_PROJECT;

GRANT CREATE SESSION,
CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE,
CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE,
CREATE ANY TRIGGER, ALTER ANY TRIGGER, DROP ANY TRIGGER,
CREATE ANY PROCEDURE, ALTER ANY PROCEDURE, DROP ANY PROCEDURE
TO C##_ADMIN_DBII_PROJECT;

GRANT C##_ADMIN_DBII_PROJECT TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT C##_ADMIN_DBII_PROJECT TO C##_OLTP_ADMIN_DBII_PROJECT;

-- Allow the query SELECT to all the OLTP tables of the ROLE created to the users of the project.
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.PAGOS TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.USUARIOS TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.PLANES TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.LISTAS_REPRODUCCION TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.REPRODUCCIONES TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.ESTADISTICAS TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.FAVORITOS TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.CANCIONES TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.LISTAS_X_CANCIONES TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.GENEROS_MUSICALES TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.TOP_ARTISTAS_MENSUALES TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.ARTISTAS TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.GRUPOS TO C##_OLAP_ADMIN_DBII_PROJECT;
GRANT SELECT ON C##_OLTP_ADMIN_DBII_PROJECT.ARTISTAS_GRUPOS TO C##_OLAP_ADMIN_DBII_PROJECT;


-- Query to show the DML permissions that have a rol or user
-- SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'C##_ADMIN_DBII_PROJECT';
-- Query to show the DDL permissions that have a rol
-- SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'C##_ADMIN_DBII_PROJECT';

-- SELECT * FROM DBA_ROLES; -- Ver todos los role existentes.
-- SELECT * FROM DBA_USERS; -- Ver todos los usuarios existentes.

